### ISSUE TITLE
Support continuous shooting still images (possibly videos too)

### ISSUE THREAD

**Issue by ayanyev** [commonsguy/cwac-cam2#139]
It will be good to have an option not to return RESULT_OK to onActivityResult each time the picture was taken and continue shooting without restarting camera

**Comment by commonsguy** [comment]
That is well outside the scope of the library, given its current API and stated purpose. It is rather unlikely that I will add this, which is why I am going to close the issue rather than have it linger for years.

If this ability is important to you, I suggest that you work directly with the camera APIs.
