### ISSUE TITLE
Aspect Ratio Issue in 16:9 device

### ISSUE THREAD

**Issue by laltukumar-1473** [commonsguy/cwac-cam2#226]
I am using 0.4.4 version and tested from 16:9 device,the image captured is in 4:3 its not coming in full screen  while viewing in 16:9 mobile device. The scenario is observable in demo application also.
Can you tell me how to resolve it.

**Comment by commonsguy** [comment]
> tested from 16:9 device

I am assuming that you mean a device with a 16:9 screen.

> the image captured is in 4:3 

That is perfectly normal. The captured image resolution is not related to:

- the physical size of the screen,
- the available space for the preview `TextureView`, or
- the available preview resolutions from the camera

> Can you tell me how to resolve it.

Use the camera APIs directly, so that you have complete control over preview and picture resolutions. This library does not offer such control.
