### ISSUE TITLE
Take photo without finish CameraActivity

### ISSUE THREAD

**Issue by twoteatome** [commonsguy/cwac-cam2#264]
Whenever I take a photo, it finish CameraActivity. Is there any way to fix it ? I want to take photo and then save picture in background thread, not show preview nor quit taking photo screen (like default camera mobile app). Thank you very much

**Comment by commonsguy** [comment]
> I want to take photo and then save picture in background thread, not show preview nor quit taking photo screen

That is outside the scope of this library.

> like default camera mobile app

First, there are thousands of Android device models, with hundreds of different "default camera mobile app" implementations among them. I doubt that you have tried them all.

Second, to the best of my knowledge, exactly zero of them offer what you want *when started via `ACTION_IMAGE_CAPTURE`*. That is because the `ACTION_IMAGE_CAPTURE` API does not support your use case.

This library is designed to be a replacement for `ACTION_IMAGE_CAPTURE`, with the camera code being included in the app (rather than relying on third-party camera apps) and with a bit more configurability.
