### ISSUE TITLE
Using the library without the ui

### ISSUE THREAD

**Issue by emmaguy** [commonsguy/cwac-cam2#302]
I'm curious to know whether you have any plans to decouple the functionality of this library with the ui? I have a use case where I need to be able to customise much more of the ui that what's allowed with this library (and I imagine many others do as well).

This library is well tested on a number of devices, so not being able to use it because we want a custom ui seems like a huge pity. Is it this way because of lifecycle intricacies or for other reasons? 

I realise there are alternative libraries out there - most notably www.github.com/google/cameraview, but it far less mature that this one (and it also doesn't support videos).

**Comment by commonsguy** [comment]
This is an issue tracker. Please use the [CommonsWare Community's CWAC category](https://community.commonsware.com/c/cwac) for general Q&A.

> I'm curious to know whether you have any plans to decouple the functionality of this library with the ui?

In terms of documented and supported APIs? No, not so long as I am also handling the UI itself.

Now, the code base is open source, and so you're welcome to do what you want. However, that is unsupported in general, insofar as I'm not going to try to chase down bugs or whatnot that can't be reproduced by the standard UI.

> Is it this way because of lifecycle intricacies or for other reasons?

It is because this library is at best a hobby, or a public service. I have no business model for this library, and if anything, I need to spend less time on it, not more. Fewer people are subscribing to my book or hiring my services, and so I have less time to spend on things like this.

And, as my original CWAC-Cam library demonstrated, lots of people have lots of different use cases ("I want the previews to fill the screen!" "I want the previews to show exactly what the picture will show!" "I want the previews to be square!", "I want the previews to be round!", "I want the previews to be a Klein bottle!"). My objective for this library is to be a bit more flexible than `ACTION_IMAGE_CAPTURE`, but that's it, because I have to limit the scope.

If somebody has the itch to scratch to create a successor to this library, one with both a super-flexible UI *and* this library's base engine, they should post a proposal to the [CommonsWare Community's CWAC category](https://community.commonsware.com/c/cwac). In principle, I'll be happy to contribute code to that. But then the overall responsibility of the library lies with the one with the itch to scratch. I'll just be a contributor.

(and, no, I do not want to try to do that sort of thing directly here, as that means that I'm responsible for the library)

If you have additional questions or concerns in this area, please use the [CommonsWare Community's CWAC category](https://community.commonsware.com/c/cwac).
